services:
    jaxon.ajax:
        class: Jaxon\AjaxBundle\Jaxon
        arguments:
            - "@kernel"
            - "@logger"
            - "@twig"
            - "%jaxon%"
    jaxon.controller:
        class: Jaxon\AjaxBundle\Controller\JaxonController
        arguments:
            - "@jaxon.ajax"
