services:
    _defaults: { public: true }

    jaxon.ajax.utils:
        class: Jaxon\AjaxBundle\Utils
    Jaxon\AjaxBundle\Jaxon:
        arguments:
            - '@kernel'
            - '@logger'
            - '@twig'
            - '@=service(service("jaxon.ajax.utils").getSessionService())'
            - '%jaxon%'
    Jaxon\AjaxBundle\Controller\JaxonController:
        arguments:
            - '@Jaxon\AjaxBundle\Jaxon'
