parameters:
  jaxon:
    app:
      request:
        route:                         "jaxon.ajax"
      directories:
        -
          # path: '%kernel.project_dir%/ajax'
          # namespace: \Jaxon\Ajax
          # register: false
          # separator: '' # '.' or '_'
          # protected: []

    lib:
      core:
        language:                      "en"
        encoding:                      "UTF-8"
        request:
          uri:                         "/jaxon"
        prefix:
          class:                       ""
        debug:
          on:                          false
          verbose:                     false
        error:
          handle:                      false
        js:
          lib:
          app:
          export:                      false
          minify:                      false
