services:
    jaxon.ajax.utils:
        class: Jaxon\Symfony\App\Utils
    Jaxon\Symfony\App\Jaxon:
        shared: true
        arguments:
            - '@kernel'
            - '@logger'
            - '@twig'
            - '@twig.loader.filesystem'
            - '@=service(service("jaxon.ajax.utils").getSessionService())'
            - '%jaxon%'
        tags: ['routing.route_loader']
    Jaxon\Symfony\EventListener\JaxonListener:
        shared: true
        arguments:
            - '@Jaxon\Symfony\App\Jaxon'
        tags:
            -
                name: kernel.event_listener
                event: kernel.controller
    Jaxon\Symfony\Controller\JaxonController:
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ['@service_container']]
